### ISSUE TITLE
sync to latest release version

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/helm-chart#10]
Currently the official release of Dragonfly is 0.4.2, and it migrates from Java to Go.
But in this helm chart, Dragonfly is still in 0.2.0, it is too old so we must update it.

**Maybe blocked by**:
https://github.com/dragonflyoss/Dragonfly/issues/651
https://github.com/dragonflyoss/Dragonfly/issues/679

 I think we can start to work on this helm chart after these two are solved.

**Comment by yeya24** [comment]
Since https://github.com/dragonflyoss/Dragonfly/issues/679 has been solved, I will work on this chart with release 0.4.3 first.

**Comment by yeya24** [comment]
Currently we use two helm charts to deploy supernode and dfclient. However I think it should be one helm chart to deploy supernode and dfclient together. WDYT? @allencloud @Starnop

**Comment by yeya24** [comment]
Updated: Since dragonfly 1.0.0 is released, we should update this helm chart as well.

**Comment by starnop** [comment]
> Updated: Since dragonfly 1.0.0 is released, we should update this helm chart as well.

Updated with #12

**Comment by yeya24** [comment]
@Starnop  I' ll check and test it this weekend.

**Comment by yeya24** [comment]
Close this since merging #12. The next thing we should do is adding docs. @Starnop
